[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "artifacts"
libs = ["lib"]
 
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/v4-core/=node_modules/@uniswap/v4-core/"
] 